version: "3.8"
services:
  # Redis for task and result queues
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # NGINX load balancer
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - coordinator1
      - coordinator2

  # Coordinator 1
  coordinator1:
    build:
      context: ./coordinator
    container_name: coordinator1
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "8081:8081"

  # Coordinator 2
  coordinator2:
    build:
      context: ./coordinator
    container_name: coordinator2
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "8082:8082"

  # Worker 1
  worker1:
    build:
      context: ./worker
    container_name: worker1
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  # Worker 2
  worker2:
    build:
      context: ./worker
    container_name: worker2
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  # Client (can be run locally, not containerized)
