apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coordinator-ingress
  namespace: cicd
spec:
  rules:
    - host: 52.166.109.93.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coordinator
                port:
                  number: 3000
