apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3100 # ✅ Change Grafana's internal port to 3100
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "3100" # ✅ Change Grafana port setting
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3100 # ✅ Change Grafana's service port to 3100
      targetPort: 3100
  type: ClusterIP
