apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: cicd
spec:
  replicas: 3 # Ensure at least 3 workers start initially
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: maso778/worker:latest
          imagePullPolicy: Always # Ensure latest image is pulled
          ports:
            - containerPort: 5001
          env:
            - name: WORKER_PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://root:uUfHB4MekN@my-mongo-release-mongodb-0.my-mongo-release-mongodb-headless.mongodb:27017/admin?replicaSet=rs0&authMechanism=SCRAM-SHA-256"

          # ✅ Resource limits for better scaling
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          # ✅ Readiness probe (checks if worker is ready to accept traffic)
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10 # Wait longer before marking ready
            periodSeconds: 5
            failureThreshold: 6 # Allow more failures before removing from service

          # ✅ Liveness probe (checks if worker is still running)
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10 # Give worker time to start before checks
            periodSeconds: 10
            failureThreshold: 6 # Allow more failures before restarting worker
